import {
  FolderTree,
  LayoutDashboard,
  Package,
  ShoppingBag,
  Star,
  Users,
} from "lucide-react";
import { ROUTES } from "@/constants/routes";

export const ADMIN_NAV = [
  {
    href: ROUTES.ADMIN.DASHBOARD,
    label: "Dashboard",
    description: "Overview & insights",
    icon: LayoutDashboard,
  },
  {
    href: ROUTES.ADMIN.PRODUCTS,
    label: "Products",
    description: "Catalog & variants",
    icon: Package,
  },
  {
    href: ROUTES.ADMIN.CATEGORIES,
    label: "Categories",
    description: "Collections",
    icon: FolderTree,
  },
  {
    href: ROUTES.ADMIN.ORDERS,
    label: "Orders",
    description: "Fulfillment",
    icon: ShoppingBag,
  },
  {
    href: ROUTES.ADMIN.USERS,
    label: "Users",
    description: "Customers & roles",
    icon: Users,
  },
  {
    href: ROUTES.ADMIN.REVIEWS,
    label: "Reviews",
    description: "Moderation",
    icon: Star,
  },
] as const;

export const ADMIN_COPY = {
  brand: "VS OilMill",
  panelLabel: "Admin Console",
  storefront: "View storefront",
  signOut: "Sign out",
} as const;

export const ADMIN_ACTIONS = {
  add: "Add",
  edit: "Edit",
  save: "Save",
  saving: "Saving…",
  cancel: "Cancel",
  close: "Close",
  delete: "Delete",
  created: "Created",
  updated: "Updated",
  deleted: "Deleted",
  deleteFailed: "Delete failed",
  updateFailed: "Update failed",
  createFailed: "Create failed",
  confirmDelete: "Delete this item? This cannot be undone.",
} as const;

export const ADMIN_USERS_COPY = {
  title: "Users",
  description:
    "Create, edit, and remove accounts. New sign-ups default to user.",
  addButton: "Add user",
  addTitle: "Add user",
  editTitle: "Edit user",
  addSubmit: "Create user",
  empty: "No users yet.",
  adding: "Creating…",
  tableUser: "User",
  tableEmail: "Email",
  tableRole: "Role",
  tableActions: "Actions",
  roleLabel: "Role",
  passwordOptional: "Leave blank to keep the current password",
  userCreated: "User created",
  userUpdated: "User updated",
  userDeleted: "User deleted",
  roleUpdated: "Role updated. Ask the user to sign in again.",
  updateFailed: "Could not update user",
  createFailed: "Could not create user",
} as const;

export const ADMIN_CATEGORY_COPY = {
  title: "Categories",
  description: "Create, edit, and delete shop collections.",
  addButton: "Add category",
  createTitle: "Create category",
  editTitle: "Edit category",
  empty: "No categories yet.",
  name: "Name",
  badge: "Badge",
  descriptionLabel: "Description",
  active: "Active",
  submit: "Create category",
  created: "Category created",
  updated: "Category updated",
  deleted: "Category deleted",
  inactive: "inactive",
  createFailed: "Failed to create category",
} as const;

export const ADMIN_ORDERS_COPY = {
  title: "Orders",
  description: "Create orders, update fulfillment or payment, and delete records.",
  addButton: "Add order",
  createTitle: "Create order",
  submit: "Create order",
  creating: "Creating…",
  created: "Order created",
  deleted: "Order deleted",
  updated: "Order updated",
  paymentLabel: "Payment",
  statusLabel: "Status",
  tableCustomer: "Customer",
  tableDate: "Date",
  tableItems: "Items",
  tableTotal: "Total",
  tableStatus: "Status",
  tablePayment: "Payment",
  tableActions: "Actions",
  itemsSuffix: "items",
  productLabel: "Product",
  variantLabel: "Variant",
  quantityLabel: "Qty",
  addItem: "Add item",
  itemsLabel: "Items",
  noItems: "Add at least one item",
  notesLabel: "Notes",
  fullName: "Full name",
  phone: "Phone",
  email: "Email",
  line1: "Address line 1",
  city: "City",
  state: "State",
  pincode: "PIN code",
  empty: "No orders yet.",
  viewDetails: "View full details",
  view: "View",
  backToOrders: "Back to orders",
  detailTitle: "Order detail",
  customerTitle: "Customer & shipping",
  paymentTitle: "Payment & status",
  phonepeOrder: "PhonePe order",
  itemsTitle: "Items",
  subtotal: "Subtotal",
  shipping: "Shipping",
  tax: "Tax",
  total: "Total",
} as const;

export const ADMIN_PRODUCTS_COPY = {
  title: "Products",
  description: "Manage oils, ghee, variants, pricing, and SEO.",
  addButton: "Add product",
} as const;

export const ADMIN_REVIEWS_COPY = {
  title: "Reviews",
  description: "Approve, hide, or delete customer feedback.",
  approve: "Approve",
  hide: "Hide",
  deleted: "Review deleted",
  empty: "No reviews yet.",
  approved: "Approved",
  pending: "Pending",
} as const;
