export const API_ENDPOINTS = {
  PRODUCTS: "/api/products",
  PRODUCT: (id: string) => `/api/products/${id}`,
  CATEGORIES: "/api/categories",
  CATEGORY: (id: string) => `/api/categories/${id}`,
  ORDERS: "/api/orders",
  ORDER: (id: string) => `/api/orders/${id}`,
  REVIEWS: "/api/reviews",
  USER_PROFILE: "/api/user/profile",
  USER_ADDRESSES: "/api/user/addresses",
  USER_PASSWORD: "/api/user/password",
  AUTH_FORGOT_PASSWORD: "/api/auth/forgot-password",
  AUTH_RESET_PASSWORD: "/api/auth/reset-password",
  ADMIN_ORDER_REFUND: (id: string) => `/api/admin/orders/${id}/refund`,
  PAYMENT_PHONEPE: "/api/payment/phonepe",
  PAYMENT_STATUS: "/api/payment/phonepe/status",
  PAYMENT_CALLBACK: "/api/payment/phonepe/callback",
  AUTH_REGISTER: "/api/auth/register",
  ADMIN_STATS: "/api/admin/stats",
  ADMIN_USERS: "/api/admin/users",
  ADMIN_USER: (id: string) => `/api/admin/users/${id}`,
  ADMIN_ORDERS: "/api/admin/orders",
  ADMIN_ORDER: (id: string) => `/api/admin/orders/${id}`,
  ADMIN_REVIEWS: "/api/admin/reviews",
} as const;
