export const ROUTES = {
  HOME: "/",
  SHOP: "/shop",
  BESTSELLERS: "/bestsellers",
  CATEGORY: (slug: string) => `/categories/${slug}`,
  PRODUCT: (slug: string) => `/products/${slug}`,
  CART: "/cart",
  CHECKOUT: "/checkout",
  ORDERS: "/orders",
  ORDER_DETAIL: (id: string) => `/orders/${id}`,
  ORDER_CONFIRMATION: (id: string) => `/orders/${id}/confirmation`,
  PROFILE: "/profile",
  LOGIN: "/login",
  REGISTER: "/register",
  ABOUT: "/about",
  CONTACT: "/contact",
  FAQS: "/faqs",
  PRIVACY: "/privacy",
  TERMS: "/terms",
  SHIPPING: "/shipping",
  REFUND: "/refund",
  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    PRODUCTS: "/admin/products",
    PRODUCT_NEW: "/admin/products/new",
    PRODUCT_EDIT: (id: string) => `/admin/products/${id}`,
    CATEGORIES: "/admin/categories",
    ORDERS: "/admin/orders",
    ORDER_DETAIL: (id: string) => `/admin/orders/${id}`,
    USERS: "/admin/users",
    REVIEWS: "/admin/reviews",
  },
} as const;

export const CART_STORAGE_KEY = "vsoilmill-cart";
